version: "3"
services:
  discount-api:
    image: hashorg/hash-mock-discount-service
    ports:
      - "50051:50051"
  app:
    image: hash-shop-api    
    depends_on:
      - discount-api
    ports:
      - "8080:80"
    environment:
      DATABASE: "Database/products.json"
      DISCOUNT_API_DATABASE: "http://localhost:50051/"
      BLACK_FRIDAY_DATE: "04/15/2022"

