version: "3"
services:
  hash-discount-api:
    image: hashorg/hash-mock-discount-service
    ports:
      - "50051:50051"
    networks:
      - network-hash
  hash-shop-api:
    image: netososilva/hash-shop-api    
    depends_on:
      - hash-discount-api
    networks:
      - network-hash
    ports:
      - "8080:80"
    environment:
      DATABASE: "Database/products.json"
      DISCOUNT_API_DATABASE: "http://hash-discount-api:50051/"
      BLACK_FRIDAY_DATE: "04/15/2022"

networks:
  network-hash:
    driver: bridge